name: sleep
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2 # لإدارة الحالة
  shared_preferences: ^2.5.2  # لتخزين الإعدادات
  flutter_local_notifications: ^18.0.1 # للإشعارات
  timezone: ^0.10.0  # مطلوب للإشعارات
  permission_handler: ^11.4.0  # للتعامل مع الأذونات
  fl_chart: ^0.65.0 # تحديث الإصدار إلى الأحدث
  url_launcher: ^6.3.1    # لفتح الروابط الخارجية

  flutter_launcher_icons: ^0.14.3 # لي اضافه ايقونه للتطبيق
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/imageapp.jpg"
  # بعد اضافه هذا الاكواد قم بكتابه الامر ده 
  # flutter pub run flutter_launcher_icons:main
  # وسوف تجد الايقونه قد تم تغيرها
  # لو بعد كده عاوز تستبدل ايقونه قم بحذف الايقونه القديمه واضف الايقونه الجديده واعد تشغيل الامر السابق
  # وسوف تجد الايقونه قد تم تغيرها
  # واستخدم اوامر دي بعدها
  # flutter clean
  # flutter pub get
  # flutter pub run flutter_launcher_icons:main


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700